# Generated by Django 4.2.7 on 2023-11-14 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=255, verbose_name='item name')),
                ('price', models.IntegerField(verbose_name='item price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('expiration_date', models.CharField(max_length=255, verbose_name='expiration date')),
                ('paymet', models.CharField(choices=[('UZCARD', 'uzcard'), ('HUMO', 'humo')], default='UZCARD', max_length=9)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='category')),
            ],
        ),
    ]
